### ISSUE TITLE
PmPro Member Directory Add On plugin corrupts website database rendering it unusable

### ISSUE THREAD

**Issue by ricschug** [strangerstudios/pmpro-member-directory#132]
It is not clear, from reading the plugin details, if I should put my issue here or in the PMPro Support website. I am not trying to make additional work simply to get my issue resolved. This is a duplicate of a ticket I put in the PMPro Support website the other day. Feel free to close which ever one is not needed.
Problem is when I install the Member Directory Add On plugin as soon as I activate it my database becomes corrupted. All the site links produce the same incorrect page in the browser. The URL window at the top of the browser is correct but the wrong page is displayed. It is always the same page regardless of the link shown.
Next I deactivate the plugin and still get the same page as when activated but now the browser URL window only displays the base website not the rest of the link path. Note that all the permalinks on all pages are still correct but nothings works. At this point my database is not longer usable. So far I have only run this on my staging instance so production remains fine.

**Comment by JarrydLong** [comment]
Hi there

We're unable to replicate the issue you're experiencing locally - because of this, this is likely an issue specific to your site. I can however confirm that it doesn't corrupt the database as we don't make any alterations to the database. 

I am working with you on our Member Support Forums to resolve this issue as soon as possible though.
