### ISSUE TITLE
Display custom fields based on user's current membership level

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-member-directory#16]
Currently the profile / directory shows custom fields if they are not empty but do not take the user's current level into consideration.

If the user has Level 2 and fills out custom fields that are assigned to only show on level 2 and then changes their membership level (i.e. to level 1) the fields still show up on both the directory and user profile.

**Comment by ideadude** [comment]
Related, we could at least add a class to the div for each user that includes their level id to make it easier to add styles specific to a level, e.g. Level 2 users are premium and should be highlighted.

pmpro-member-directory-item-level-1 That's long, but something like that. Maybe a couple of css classes. Kim would know better what's typical here.

**Comment by JarrydLong** [comment]
Lets make use of the `pmprorh_checkFieldForLevel` function to check if the field is allowed for that specific RH field.

**Comment by kimcoleman** [comment]
In the new branch where fields are merged into core, this would be the function renamed: https://github.com/strangerstudios/paid-memberships-pro/blob/user-fields-admin/includes/fields.php#L97-L100

**Comment by JarrydLong** [comment]
The `pmpro_check_field_for_level` and `pmprorh_checkFieldForLevel` functions expect a $field object but we don't have this on a directory or profile template, only an array that looks like this: 

`
array (size=2)
  0 => string 'Company' (length=7)
  1 => string 'company' (length=7)
`

and when dumping out a meta field value, we get the value but no object: 

`C:\wamp64\www\pmpro\wp-content\plugins\pmpro-member-directory\templates\profile.php:360:string 'Yoyo Craft' (length=10)`

Could we consider creating a wrapper function that checks if a field applies to the current level, without providing a level object. 

The `pmprorh_pmpro_after_checkout` function loops through the global $pmprorh_registration_fields array and then checks if the field applies to that level. I think it would be better if we added something like this in the RH Add On rather than the Member Directory
