### ISSUE TITLE
 Feature request: MMPU compatibility 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#28]
A user has requested compatibility with the MMPU Add On. They reported that members show up as many times in the directory list as levels they hold (members with 3 levels show up 3 times).

The level name that shows is always the same. 

My recommendation would be that members only show up once in the listing and the level names that display for their individual directory listing/profile are either all levels they hold or the levels they hold that are allowed to be included in the directory.

**Comment by topher1kenobe** [comment]
Here's a screenshot.
<img width="1113" alt="Screen Shot 2019-06-26 at 9 26 55 PM" src="https://user-images.githubusercontent.com/341412/60226448-41811280-9859-11e9-9072-3eb2b54654e5.png">

There are several examples here, but the ones pointed out are that Joshua is both a Church Pastor and a Ministry Partner, so he shows up twice.

One scenario is to list him once, and in the group col show "Church Pastor, Ministry Partner".

Personally I don't want that scenario because it would mess up the javascript sorting I'm doing.  What I'd like is for Joshua to be listed once, with only one group showing.

I need this this week, which I know is a tight turnaround to ask. If that's not feasible then I'll write my own SQL and generate my own table, since my data set is so simple.

Please let me know what the options are here.

**Comment by andrewlimaza** [comment]
@topher1kenobe I'll be working through this, this week. Our SQL for retrieving the data is to use `GROUP BY` which should remove duplicates from the directory list.

**Comment by andrewlimaza** [comment]
I have tried to recreate this issue but I am unable to do so. I'll reach out directly to you @topher1kenobe :)

**Comment by kimcoleman** [comment]
We haven't been able to replicate the duplicate entry issue, however the latest release includes support to show a comma-separated list of level names when applicable.

@topher1kenobe if you are still seeing a duplicate name, please let us know and I will reopen the issue.
